name: rsa_oaep_dart
description: "Pure Dart implementation of RSAES-OAEP (PKCS#1 v2.2)"
version: 0.1.5

homepage: https://github.com/gabrielscota/rsa_oaep_dart
repository: https://github.com/gabrielscota/rsa_oaep_dart
issue_tracker: https://github.com/gabrielscota/rsa_oaep_dart/issues
documentation: https://github.com/gabrielscota/rsa_oaep_dart#readme
license: MIT

environment:
  sdk: ^3.0.0

dependencies:
  asn1lib: ^1.6.4
  basic_utils: ^5.8.2
  pointycastle: ^4.0.0

dev_dependencies:
  flutter_lints: ^5.0.0
  test: ^1.26.2
